/**
 * Central subjects registry for NaijaAcademy.
 * ALL screens import from here — no more hardcoded subject lists.
 * Auto-populated from cbt_questions.json + lessonsData by the scraper.
 */

export type Topic = {
  name: string;
  desc: string;
};

export type SubjectConfig = {
  id: string;
  name: string;
  desc: string;
  icon: string;
  colorKey: 'accent' | 'orange' | 'warning' | 'blue' | 'success';
  bgKey:    'accentDim' | 'orangeDim' | 'warningDim' | 'blueDim';
  topics: Topic[];
  examTypes: ('JAMB' | 'WAEC' | 'NECO' | 'COMMON_ENTRANCE')[];
};

export const SUBJECTS: SubjectConfig[] = [
  {
    id: 'maths',
    name: 'Mathematics',
    desc: 'Number theory, algebra, calculus, statistics & more',
    icon: 'calculator-outline',
    colorKey: 'accent',
    bgKey:    'accentDim',
    examTypes: ['JAMB', 'WAEC', 'NECO'],
    topics: [
      { name: 'Number and Numeration',       desc: 'Integers, fractions, indices, surds' },
      { name: 'Algebra',                     desc: 'Equations, inequalities, polynomials' },
      { name: 'Geometry',                    desc: 'Shapes, angles, loci, constructions' },
      { name: 'Trigonometry',                desc: 'Sin, cos, tan and their identities' },
      { name: 'Calculus',                    desc: 'Differentiation and integration' },
      { name: 'Statistics and Probability',  desc: 'Data analysis, mean, variance, distributions' },
      { name: 'Matrices and Determinants',   desc: 'Matrix operations and applications' },
      { name: 'Coordinate Geometry',         desc: 'Lines, circles, parabolas on Cartesian plane' },
      { name: 'Mensuration',                 desc: 'Areas, volumes, surface areas' },
      { name: 'Vectors',                     desc: 'Vector operations and applications' },
      { name: 'Indices and Logarithms',      desc: 'Laws of indices and logarithmic functions' },
      { name: 'Sequences and Series',        desc: 'AP, GP, sum of series' },
      { name: 'Sets and Logic',              desc: 'Set theory, Venn diagrams, Boolean logic' },
    ],
  },
  {
    id: 'english',
    name: 'English Language',
    desc: 'Comprehension, grammar, writing and oral skills',
    icon: 'book-outline',
    colorKey: 'blue',
    bgKey:    'blueDim',
    examTypes: ['JAMB', 'WAEC', 'NECO'],
    topics: [
      { name: 'Comprehension',               desc: 'Reading and inference skills' },
      { name: 'Summary Writing',             desc: 'Identifying key points from passages' },
      { name: 'Lexis and Structure',         desc: 'Vocabulary, grammar, usage' },
      { name: 'Essay Writing',               desc: 'Formal, informal, narrative, descriptive' },
      { name: 'Oral English',                desc: 'Phonetics, stress, intonation' },
      { name: 'Figures of Speech',           desc: 'Metaphor, simile, irony and more' },
      { name: 'Concord and Agreement',       desc: 'Subject-verb agreement rules' },
      { name: 'Parts of Speech',             desc: 'Nouns, pronouns, verbs, adjectives...' },
      { name: 'Tenses',                      desc: 'Simple, continuous, perfect, conditional' },
      { name: 'Direct and Indirect Speech',  desc: 'Reported speech transformation' },
      { name: 'Sentence Structure',          desc: 'Clauses, phrases, sentence types' },
    ],
  },
  {
    id: 'physics',
    name: 'Physics',
    desc: 'Mechanics, waves, electricity, thermodynamics & more',
    icon: 'flash-outline',
    colorKey: 'orange',
    bgKey:    'orangeDim',
    examTypes: ['JAMB', 'WAEC', 'NECO'],
    topics: [
      { name: 'Kinematics',                    desc: 'Motion, velocity, acceleration, graphs' },
      { name: 'Dynamics',                      desc: "Newton's laws, momentum, forces" },
      { name: 'Projectile Motion',             desc: '2D motion under gravity' },
      { name: 'Work Energy and Power',         desc: 'Conservation of energy, efficiency' },
      { name: 'Waves and Sound',               desc: 'Wave properties, superposition, resonance' },
      { name: 'Light and Optics',              desc: 'Reflection, refraction, lenses, mirrors' },
      { name: 'Electricity and Magnetism',     desc: 'Fields, circuits, electromagnetic force' },
      { name: 'Heat and Temperature',          desc: 'Thermal expansion, specific heat capacity' },
      { name: 'Atomic and Nuclear Physics',    desc: 'Radioactivity, fission, fusion' },
      { name: 'Electromagnetic Induction',     desc: 'Faraday, Lenz, generators, motors' },
      { name: 'Simple Harmonic Motion',        desc: 'Pendulums, springs, oscillations' },
      { name: 'Gravitational Field',           desc: "Newton's law of gravitation, satellites" },
      { name: 'Gas Laws',                      desc: 'Boyle, Charles, Avogadro, ideal gas' },
    ],
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    desc: 'Atomic structure, reactions, organic chemistry & more',
    icon: 'flask-outline',
    colorKey: 'warning',
    bgKey:    'warningDim',
    examTypes: ['JAMB', 'WAEC', 'NECO'],
    topics: [
      { name: 'Atomic Structure',        desc: 'Protons, neutrons, electrons, orbitals' },
      { name: 'Chemical Bonding',        desc: 'Ionic, covalent, metallic, hydrogen bonds' },
      { name: 'Acids Bases and Salts',   desc: 'pH, neutralisation, titration' },
      { name: 'Organic Chemistry',       desc: 'Hydrocarbons, functional groups, reactions' },
      { name: 'Electrochemistry',        desc: 'Electrolysis, electrodes, Faraday laws' },
      { name: 'Stoichiometry',           desc: 'Moles, ratios, empirical formula' },
      { name: 'Periodic Table',          desc: 'Groups, periods, trends in properties' },
      { name: 'Redox Reactions',         desc: 'Oxidation states, balancing redox equations' },
      { name: 'Gas Laws',                desc: 'Ideal gas, Boyle, Charles, Dalton' },
      { name: 'Rates of Reaction',       desc: 'Factors affecting rate, catalysis' },
      { name: 'Equilibrium',             desc: "Le Chatelier's principle, Kc and Kp" },
      { name: 'Hydrocarbons',            desc: 'Alkanes, alkenes, alkynes, benzene' },
      { name: 'Metals and Non-Metals',   desc: 'Extraction, properties, uses' },
    ],
  },
  {
    id: 'biology',
    name: 'Biology',
    desc: 'Cell biology, genetics, ecology, human physiology & more',
    icon: 'leaf-outline',
    colorKey: 'accent',
    bgKey:    'accentDim',
    examTypes: ['JAMB', 'WAEC', 'NECO'],
    topics: [
      { name: 'Cell Biology',                       desc: 'Cell structure, mitosis, meiosis' },
      { name: 'Genetics and Heredity',              desc: 'DNA, chromosomes, Mendelian genetics' },
      { name: 'Evolution',                          desc: "Darwin's theory, natural selection" },
      { name: 'Ecology and Environment',            desc: 'Ecosystems, food webs, conservation' },
      { name: 'Human Physiology',                   desc: 'Organ systems and their functions' },
      { name: 'Plant Biology',                      desc: 'Photosynthesis, transpiration, tropisms' },
      { name: 'Microorganisms and Disease',         desc: 'Bacteria, viruses, immunity' },
      { name: 'Reproduction',                       desc: 'Sexual and asexual reproduction' },
      { name: 'Classification of Living Things',    desc: 'Taxonomy, kingdoms, phylogeny' },
      { name: 'Nutrition in Plants and Animals',    desc: 'Photosynthesis, digestion, absorption' },
      { name: 'Excretion',                          desc: 'Kidneys, liver, skin, lungs' },
      { name: 'Respiration',                        desc: 'Aerobic and anaerobic respiration' },
      { name: 'Transport in Plants and Animals',    desc: 'Xylem, phloem, circulatory system' },
    ],
  },
  {
    id: 'government',
    name: 'Government',
    desc: 'Political systems, Nigerian constitution, international relations',
    icon: 'business-outline',
    colorKey: 'blue',
    bgKey:    'blueDim',
    examTypes: ['JAMB', 'WAEC', 'NECO'],
    topics: [
      { name: 'Basic Concepts in Government',       desc: 'Sovereignty, legitimacy, power, authority' },
      { name: 'Types of Government',                desc: 'Democracy, monarchy, oligarchy, military' },
      { name: 'The Nigerian Constitution',          desc: 'History and provisions of the constitution' },
      { name: 'The Legislature',                    desc: 'National Assembly, law-making process' },
      { name: 'The Executive',                      desc: 'President, governors, Federal Executive Council' },
      { name: 'The Judiciary',                      desc: 'Courts, independence of the judiciary' },
      { name: 'Federalism',                         desc: 'Federal, state and local government' },
      { name: 'Political Parties and Electoral Systems', desc: 'Party systems, elections, INEC' },
      { name: 'Foreign Policy',                     desc: "Nigeria's foreign relations and objectives" },
      { name: 'International Organisations',        desc: 'UN, AU, ECOWAS, Commonwealth' },
      { name: 'Colonialism and Nationalism',        desc: 'Colonial rule and the independence struggle' },
      { name: 'Democracy',                          desc: 'Principles, pillars and challenges' },
    ],
  },
  {
    id: 'economics',
    name: 'Economics',
    desc: 'Micro and macro economics, trade, banking, development',
    icon: 'trending-up-outline',
    colorKey: 'warning',
    bgKey:    'warningDim',
    examTypes: ['JAMB', 'WAEC', 'NECO'],
    topics: [
      { name: 'Demand and Supply',         desc: 'Laws, determinants, elasticity' },
      { name: 'Market Structures',         desc: 'Perfect competition, monopoly, oligopoly' },
      { name: 'National Income',           desc: 'GDP, GNP, NNP, measurement methods' },
      { name: 'Money and Banking',         desc: 'Functions of money, CBN, commercial banks' },
      { name: 'International Trade',       desc: 'Balance of payments, exchange rates, tariffs' },
      { name: 'Public Finance',            desc: 'Government revenue, expenditure, taxation' },
      { name: 'Economic Development',      desc: 'Indicators, obstacles, growth strategies' },
      { name: 'Population',               desc: 'Population growth, demographic transition' },
      { name: 'Production and Cost',       desc: 'Factors of production, cost curves' },
      { name: 'Price Determination',       desc: 'Market equilibrium, price controls' },
      { name: 'Labour and Capital',        desc: 'Wage determination, capital formation' },
      { name: 'Agricultural Economics',    desc: 'Land tenure, farming systems, subsidies' },
    ],
  },
  {
    id: 'literature',
    name: 'Literature in English',
    desc: 'Prose, poetry, drama, literary devices, African literature',
    icon: 'journal-outline',
    colorKey: 'accent',
    bgKey:    'accentDim',
    examTypes: ['WAEC', 'NECO'],
    topics: [
      { name: 'Prose Fiction',                     desc: 'Novel structure, character, theme, setting' },
      { name: 'Poetry',                            desc: 'Types, form, imagery, analysis techniques' },
      { name: 'Drama',                             desc: 'Tragedy, comedy, staging, performance' },
      { name: 'Literary Devices and Figures of Speech', desc: 'Metaphor, irony, alliteration, symbolism' },
      { name: 'Oral Literature',                   desc: 'Folktales, proverbs, riddles, songs' },
      { name: 'African Literature',                desc: 'Key African authors and their works' },
      { name: 'Setting and Characterisation',      desc: 'Physical and social setting, character types' },
      { name: 'Theme and Plot Analysis',           desc: 'Identifying themes, narrative structure' },
      { name: 'Narrative Technique',               desc: 'Point of view, flashback, stream of consciousness' },
    ],
  },
  {
    id: 'agric',
    name: 'Agricultural Science',
    desc: 'Crop production, animal husbandry, soil science, farm management',
    icon: 'nutrition-outline',
    colorKey: 'accent',
    bgKey:    'accentDim',
    examTypes: ['WAEC', 'NECO'],
    topics: [
      { name: 'Crop Production',           desc: 'Land preparation, planting, harvesting' },
      { name: 'Animal Husbandry',          desc: 'Livestock management, poultry, fishery' },
      { name: 'Soil Science',              desc: 'Soil types, fertility, conservation' },
      { name: 'Farm Tools and Equipment',  desc: 'Hand tools, tractors, irrigation equipment' },
      { name: 'Agricultural Economics',    desc: 'Farm records, land tenure, cooperative' },
      { name: 'Pest and Disease Control',  desc: 'Pests, diseases, pesticides, IPM' },
      { name: 'Irrigation and Drainage',   desc: 'Water management systems' },
      { name: 'Forest and Fisheries',      desc: 'Forest management, aquaculture' },
      { name: 'Genetics in Agriculture',   desc: 'Breeding, hybridisation, GMOs' },
      { name: 'Farm Management',           desc: 'Planning, budgeting, farm records' },
    ],
  },
  {
    id: 'commerce',
    name: 'Commerce',
    desc: 'Trade, banking, insurance, transportation, business documents',
    icon: 'cart-outline',
    colorKey: 'orange',
    bgKey:    'orangeDim',
    examTypes: ['WAEC', 'NECO'],
    topics: [
      { name: 'Introduction to Commerce',  desc: 'Nature, scope, importance of commerce' },
      { name: 'Retail and Wholesale Trade', desc: 'Types of traders, functions, advantages' },
      { name: 'Banking',                   desc: 'Types of banks, functions, accounts, e-banking' },
      { name: 'Insurance',                 desc: 'Types, principles, documents, claims' },
      { name: 'Warehousing',               desc: 'Types, bonded warehouses, cold storage' },
      { name: 'Transportation',            desc: 'Road, rail, air, sea, pipeline' },
      { name: 'Communication',             desc: 'Telephone, internet, postal services' },
      { name: 'Advertising',               desc: 'Types of advertising, media, AIDA model' },
      { name: 'Import and Export',         desc: 'Procedures, documents, tariffs, forex' },
      { name: 'Business Documents',        desc: 'Invoice, receipt, bill of lading, LPO' },
      { name: 'Channels of Distribution', desc: 'Retailer, wholesaler, agent, direct sales' },
    ],
  },
  {
    id: 'geography',
    name: 'Geography',
    desc: 'Physical geography, human geography, map reading, Nigeria',
    icon: 'earth-outline',
    colorKey: 'blue',
    bgKey:    'blueDim',
    examTypes: ['WAEC', 'NECO'],
    topics: [
      { name: 'Map Reading and Interpretation', desc: 'Contours, scale, grid references, relief' },
      { name: 'The Earth',                      desc: 'Shape, rotation, revolution, latitude/longitude' },
      { name: 'Rocks and Minerals',             desc: 'Igneous, sedimentary, metamorphic rocks' },
      { name: 'Weather and Climate',            desc: 'Elements, climate types, pressure belts' },
      { name: 'Vegetation Zones',               desc: 'Tropical rainforest, savanna, desert' },
      { name: 'Population Geography',           desc: 'Population growth, migration, density' },
      { name: 'Settlement and Urbanisation',    desc: 'Rural and urban settlements, urban problems' },
      { name: 'Economic Geography',             desc: 'Agriculture, industry, mining, trade' },
      { name: 'Nigeria Physical Geography',     desc: "Nigeria's relief, climate, vegetation, rivers" },
      { name: 'West Africa Geography',          desc: 'Countries, rivers, resources, cooperation' },
      { name: 'Hydrology',                      desc: 'Rivers, lakes, water cycle, ocean currents' },
    ],
  },
  {
    id: 'further-maths',
    name: 'Further Mathematics',
    desc: 'Advanced algebra, calculus, statistics, complex numbers & more',
    icon: 'infinite-outline',
    colorKey: 'warning',
    bgKey:    'warningDim',
    examTypes: ['WAEC'],
    topics: [
      { name: 'Polynomials',                desc: 'Roots, factor theorem, remainder theorem' },
      { name: 'Binomial Theorem',           desc: 'Expansion, coefficients, applications' },
      { name: 'Complex Numbers',            desc: 'Argand diagram, modulus, argument, De Moivre' },
      { name: 'Differentiation and Integration', desc: 'Advanced calculus techniques and applications' },
      { name: 'Matrices',                   desc: 'Operations, inverse, solving linear systems' },
      { name: 'Probability Distributions',  desc: 'Binomial, Poisson, normal distributions' },
      { name: 'Permutation and Combination', desc: 'Counting principles, arrangements' },
      { name: 'Vectors in 3D',              desc: 'Dot product, cross product, applications' },
      { name: 'Conic Sections',             desc: 'Parabola, ellipse, hyperbola' },
      { name: 'Differential Equations',     desc: 'First-order, second-order ODEs' },
    ],
  },
  {
    id: 'account',
    name: 'Financial Accounting',
    desc: 'Bookkeeping, final accounts, partnership, company accounts',
    icon: 'wallet-outline',
    colorKey: 'warning',
    bgKey:    'warningDim',
    examTypes: ['WAEC', 'NECO'],
    topics: [
      { name: 'Basic Accounting Concepts',          desc: 'Principles, conventions, concepts' },
      { name: 'Double Entry Bookkeeping',           desc: 'Debits, credits, journals, ledgers' },
      { name: 'Trial Balance',                      desc: 'Preparation, errors, adjustments' },
      { name: 'Final Accounts',                     desc: 'Trading, P&L, balance sheet' },
      { name: 'Cash Book',                          desc: 'Single, double, triple-column cash books' },
      { name: 'Bank Reconciliation',                desc: 'Causes of differences, reconciliation' },
      { name: 'Depreciation',                       desc: 'Methods: SLM, RBM, sum of digits' },
      { name: 'Partnership Accounts',               desc: 'Capital, current accounts, goodwill' },
      { name: 'Company Accounts',                   desc: 'Share capital, debentures, final accounts' },
      { name: 'Ratio Analysis',                     desc: 'Liquidity, profitability, activity ratios' },
      { name: 'Single Entry and Incomplete Records', desc: 'Statement of affairs, conversion' },
    ],
  },
  {
    id: 'crk',
    name: 'Christian Religious Studies',
    desc: 'Old Testament, New Testament, early church, Christian ethics',
    icon: 'heart-outline',
    colorKey: 'blue',
    bgKey:    'blueDim',
    examTypes: ['WAEC', 'NECO'],
    topics: [
      { name: 'The Old Testament',        desc: 'Creation, patriarchs, prophets, psalms' },
      { name: 'The New Testament',        desc: 'Gospels, epistles, Revelation' },
      { name: 'The Life of Jesus',        desc: 'Birth, ministry, miracles, death, resurrection' },
      { name: 'The Early Church',         desc: 'Pentecost, apostles, missionary journeys' },
      { name: 'Christian Ethics',         desc: 'Moral principles, virtues, social responsibilities' },
      { name: 'The Holy Spirit',          desc: 'Nature, gifts, fruits of the Holy Spirit' },
      { name: 'Faith and Salvation',      desc: 'Justification, sanctification, grace' },
      { name: 'Prayer and Worship',       desc: 'Lord\'s Prayer, types of prayer, corporate worship' },
      { name: 'Christianity in Nigeria',  desc: 'Missionary activities, church growth, challenges' },
    ],
  },
  {
    id: 'irk',
    name: 'Islamic Studies',
    desc: 'Tauhid, Quran, Hadith, pillars of Islam, Islamic history',
    icon: 'moon-outline',
    colorKey: 'accent',
    bgKey:    'accentDim',
    examTypes: ['WAEC', 'NECO'],
    topics: [
      { name: 'Tauhid',                   desc: 'Oneness of Allah, attributes' },
      { name: 'Quran Studies',            desc: 'Revelation, preservation, recitation' },
      { name: 'Hadith',                   desc: 'Classification, importance, collections' },
      { name: 'Islamic Ethics and Morality', desc: 'Character, social conduct, values' },
      { name: 'Pillars of Islam',         desc: 'Shahada, Salah, Zakah, Sawm, Hajj' },
      { name: 'Islamic History',          desc: 'Prophet Muhammad, caliphate, Islam in Nigeria' },
      { name: 'Islamic Law',              desc: 'Sharia, Fiqh, family law, criminal law' },
      { name: 'Prayer and Worship in Islam', desc: 'Salah, Dua, Islamic calendar' },
    ],
  },
  {
    id: 'civic',
    name: 'Civic Education',
    desc: 'Democracy, human rights, rule of law, national values',
    icon: 'flag-outline',
    colorKey: 'orange',
    bgKey:    'orangeDim',
    examTypes: ['WAEC', 'NECO'],
    topics: [
      { name: 'Democracy and Governance',   desc: 'Principles, institutions, participation' },
      { name: 'Human Rights',               desc: 'Fundamental rights, UDHR, enforcement' },
      { name: 'Rule of Law',                desc: 'Equality before the law, due process' },
      { name: 'Citizenship and Identity',   desc: 'Duties, rights, Nigerian identity' },
      { name: 'Patriotism and Nationalism', desc: 'Love for country, national symbols' },
      { name: 'National Values',            desc: 'Discipline, integrity, unity, hard work' },
      { name: 'INEC and Elections',         desc: 'Electoral process, voter registration' },
      { name: 'Corruption and Anti-Corruption', desc: 'Effects of corruption, EFCC, ICPC' },
    ],
  },
  {
    id: 'technical-drawing',
    name: 'Technical Drawing',
    desc: 'Drawing instruments, projections, sectional views, dimensions',
    icon: 'pencil-outline',
    colorKey: 'warning',
    bgKey:    'warningDim',
    examTypes: ['WAEC', 'NECO'],
    topics: [
      { name: 'Instruments and Their Uses',  desc: 'T-square, compass, set squares, scales' },
      { name: 'Geometric Constructions',     desc: 'Bisection, polygons, circles, tangents' },
      { name: 'Projection Drawing',          desc: '1st and 3rd angle orthographic projection' },
      { name: 'Sectional Views',             desc: 'Full, half, revolved sections' },
      { name: 'Dimensioning',               desc: 'Standards, practices, tolerances' },
      { name: 'Isometric Drawing',           desc: 'Isometric grid, drawing solids' },
    ],
  },
];

/** Get a subject config by ID */
export function getSubject(id: string): SubjectConfig | null {
  return SUBJECTS.find(s => s.id === id) ?? null;
}

/** Get all subject IDs */
export function getAllSubjectIds(): string[] {
  return SUBJECTS.map(s => s.id);
}

/** Get subjects filtered by exam type */
export function getSubjectsByExam(examType: 'JAMB' | 'WAEC' | 'NECO' | 'COMMON_ENTRANCE'): SubjectConfig[] {
  return SUBJECTS.filter(s => s.examTypes.includes(examType));
}

/** The recommended JAMB study path (top subjects for UTME) */
export const JAMB_STUDY_PATH = [
  { subject: 'maths',     topic: 'Algebra' },
  { subject: 'physics',   topic: 'Kinematics' },
  { subject: 'chemistry', topic: 'Atomic Structure' },
  { subject: 'english',   topic: 'Comprehension' },
  { subject: 'biology',   topic: 'Cell Biology' },
  { subject: 'maths',     topic: 'Statistics and Probability' },
];
