#!/usr/bin/env python3
"""
Reads all scraped HTML lesson files from Pages/ and generates
lib/lessonsData.ts — a TypeScript map the app can import directly.
Run after scrape_content.py finishes (or any time you add new lessons).
"""

import pathlib
import json
import re

BASE_DIR = pathlib.Path(__file__).parent.parent
PAGES_DIR = BASE_DIR / "Pages"
OUT_FILE = BASE_DIR / "lib" / "lessonsData.ts"

# Map folder names to app subject IDs
FOLDER_TO_SUBJECT = {
    "biology": "biology",
    "chemistry": "chemistry",
    "maths": "maths",
    "physics": "physics",
    "english": "english",
}

# Map HTML file stem to topic name (used as display label)
def stem_to_topic(stem: str) -> str:
    return stem.replace("-", " ").title()

def build():
    data = {}  # { subjectId: { topicSlug: { title, html } } }

    for folder, subj_id in FOLDER_TO_SUBJECT.items():
        subj_dir = PAGES_DIR / folder
        if not subj_dir.exists():
            print(f"  [skip] {subj_dir} — does not exist")
            continue

        data[subj_id] = {}
        for html_file in sorted(subj_dir.glob("*.html")):
            # Skip index/list pages
            if html_file.stem in ("index", subj_id, folder):
                continue
            topic_key = html_file.stem          # e.g. "cell-biology"
            topic_title = stem_to_topic(html_file.stem)  # e.g. "Cell Biology"
            html_content = html_file.read_text(encoding="utf-8")
            data[subj_id][topic_key] = {
                "title": topic_title,
                "html": html_content,
            }
        print(f"  {subj_id}: {len(data[subj_id])} lessons")

    # Serialise as a TS module
    ts_lines = [
        "// AUTO-GENERATED by scripts/build_lessons_data.py",
        "// Do not edit manually — re-run the script after scraping.",
        "",
        "export type LessonContent = {",
        "  title: string;",
        "  html: string;",
        "};",
        "",
        "export type LessonsMap = Record<string, Record<string, LessonContent>>;",
        "",
        "const lessonsData: LessonsMap = " + json.dumps(data, indent=2, ensure_ascii=False) + ";",
        "",
        "export default lessonsData;",
        "",
        "/** Return lesson HTML for a subject + topic slug, or null if not found. */",
        "export function getLesson(subjectId: string, topicSlug: string): LessonContent | null {",
        "  return lessonsData[subjectId]?.[topicSlug] ?? null;",
        "}",
        "",
        "/** Return all topic slugs for a subject. */",
        "export function getTopicSlugs(subjectId: string): string[] {",
        "  return Object.keys(lessonsData[subjectId] ?? {});",
        "}",
    ]

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(ts_lines), encoding="utf-8")
    total = sum(len(v) for v in data.values())
    print(f"\n✓ Written {total} lessons to {OUT_FILE.relative_to(BASE_DIR)}")

if __name__ == "__main__":
    print("Building lessonsData.ts from Pages/...")
    build()
