#!/usr/bin/env node
/**
 * Fetches Supabase config from GitHub Repository Variables and writes .env
 * so both the Expo app and web build can pick them up automatically.
 *
 * One-time setup (run once in the Replit shell):
 *   gh auth login
 *
 * Then add these as GitHub Repository Variables at:
 *   https://github.com/Tolu23456/Naija_Academy/settings/variables/actions
 *   (Settings → Secrets and variables → Actions → Variables tab)
 *   - SUPABASE_URL
 *   - SUPABASE_ANON_KEY
 *
 * After that, this script runs automatically every time the app starts
 * and keeps the .env file up to date from your GitHub repo variables.
 */

const { execSync, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ENV_PATH = path.join(__dirname, '..', '.env');
const REPO = 'Tolu23456/Naija_Academy';

// ── helpers ───────────────────────────────────────────────────────────────────

function run(cmd, args = []) {
  const result = spawnSync(cmd, args, { encoding: 'utf8' });
  if (result.error || result.status !== 0) return null;
  return (result.stdout || '').trim();
}

function ghVar(name) {
  const val = run('gh', ['variable', 'get', name, '--repo', REPO]);
  return val && val.length > 0 ? val : null;
}

function isGhAuthenticated() {
  const result = spawnSync('gh', ['auth', 'status'], { encoding: 'utf8' });
  return result.status === 0;
}

// ── main ──────────────────────────────────────────────────────────────────────

console.log('[setup-env] Fetching config from GitHub repo variables...');

// 1. Check gh authentication
if (!isGhAuthenticated()) {
  console.error(`
  ┌─────────────────────────────────────────────────────────────┐
  │  GitHub CLI is not authenticated.                           │
  │                                                             │
  │  Run this once in the shell to connect:                     │
  │    gh auth login                                            │
  │                                                             │
  │  Then add your variables at:                                │
  │  https://github.com/${REPO}/settings/variables/actions  │
  │    - SUPABASE_URL                                           │
  │    - SUPABASE_ANON_KEY                                      │
  └─────────────────────────────────────────────────────────────┘
`);
  // Don't crash — app can still run in demo/offline mode
  process.exit(0);
}

// 2. Fetch variables from GitHub
const supabaseUrl  = ghVar('SUPABASE_URL');
const supabaseKey  = ghVar('SUPABASE_ANON_KEY');

if (!supabaseUrl || !supabaseKey) {
  console.warn(`
  [setup-env] WARNING: Could not fetch one or more GitHub variables.
  Make sure these exist as Repository Variables (not Secrets):
    - SUPABASE_URL
    - SUPABASE_ANON_KEY
  Visit: https://github.com/${REPO}/settings/variables/actions
`);
  process.exit(0);
}

// 3. Write .env — Expo reads EXPO_PUBLIC_* automatically on both web and native
const envContent = [
  '# Auto-generated by scripts/setup-env.js — do not edit manually',
  `EXPO_PUBLIC_SUPABASE_URL=${supabaseUrl}`,
  `EXPO_PUBLIC_SUPABASE_ANON_KEY=${supabaseKey}`,
  '',
].join('\n');

fs.writeFileSync(ENV_PATH, envContent, 'utf8');
console.log('[setup-env] .env written successfully from GitHub variables.\n');
